### ISSUE TITLE
compiled version

### ISSUE THREAD

**Issue by Teicu** [gdgd009xcd/AutoMacroBuilder#1]
Hi 

you can please release compiled version of this extension? 

thank you

**Comment by gdgd009xcd** [comment]
Hi

Please refer to the installation instructions in the following link:
https://github.com/gdgd009xcd/AutoMacroBuilder/wiki/1.1.-Install-Setup

thank you.

2018年10月12日(金) 19:52 Gabriel <notifications@github.com>:
